mongo:
    databaseName: 'snapshot'
snapshot:
#     corePoolSize: 20
#     maxConnTotal: 80
#     queueCapacity: 20
    startDate: '2016-12-02'
#     endDate: '2016-08-25'
#     stocks:
#         - '01357'
    